# Generated by Django 3.2.2 on 2021-05-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=256)),
                ('is_open_for_requests', models.BooleanField(default=False)),
            ],
        ),
    ]
