# Generated by Django 3.2.2 on 2021-05-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
